#!/usr/bin/env python
"""Generate js/diffractionsim-web/presets.ts, the crystal data of the website simulator.

The website build of DiffractionSim (``dist/web/diffraction-sim.js``, made by
``npm run build:web``) has no Python, so its structure menu is embedded at
build time. This script writes that data with the same code the Jupyter
widget uses (``quantem.widget._diffraction_sim_crystal.prepare_crystal`` on
the ``PRESETS`` structures): Lobato kinematical factors and absorptive
Weickenmeier-Kohl Bloch couplings at 200 keV, reflections out to
k_max = 3.0 1/Å. The browser rescales the couplings for other beam energies.

The generated file (about 1 MB) is committed because the website build needs
it and regenerating it needs a quantem that is not released yet: quantem with
``quantem.diffraction.Crystal`` and ``bloch`` (electronmicroscopy/quantem
PR #297, first release after 0.1.9). If your widget environment lacks them,
run the script with the interpreter of a quantem development checkout and put
this repository's ``src`` on ``PYTHONPATH``, for example::

    PYTHONPATH=src /path/to/quantem/.venv/bin/python scripts/diffraction_sim_presets.py

Usage::

    python scripts/diffraction_sim_presets.py          # rewrite js/diffractionsim-web/presets.ts
    python scripts/diffraction_sim_presets.py --check  # compare with the committed file

``--check`` decodes both files and compares every field: strings, integers and
reflection indices exactly, the float32 reflection arrays to 1e-5 of their
largest value, and the other floats to a relative 1e-6.
"""

from __future__ import annotations

import argparse
import base64
import json
import re
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[1]
OUTPUT = REPO / "js" / "diffractionsim-web" / "presets.ts"

ENERGY_EV = 200_000.0
K_MAX = 3.0

# Structures in the website menu, in menu order (keys of PRESETS).
WEB_PRESETS = [
    "Si (diamond cubic)",
    "GaAs (zincblende)",
    "Al (fcc)",
    "Au (fcc)",
    "Fe (bcc)",
    "Ti (hcp)",
    "NaCl (rocksalt)",
    "SrTiO3 (perovskite)",
    "Al2O3 (corundum)",
]

_FLOAT32_FIELDS = ("F2", "U_re", "U_im")
_FLOAT64_FIELDS = ("cell", "recip", "positions_frac", "colors", "radii")


def generate() -> dict[str, dict]:
    """Return the crystal payload of every website preset, keyed by menu name."""
    sys.path.insert(0, str(REPO / "src"))
    from quantem.widget._diffraction_sim_crystal import prepare_crystal, preset_crystal

    return {name: prepare_crystal(preset_crystal(name), ENERGY_EV, K_MAX) for name in WEB_PRESETS}


def render_ts(presets: dict[str, dict]) -> str:
    """Format the payloads as the TypeScript module the web build imports."""
    k_max = f"{K_MAX:.1f}"
    lines = [
        "// Generated by scripts/diffraction_sim_presets.py: crystal data for the website",
        f"// simulator ({ENERGY_EV / 1e3:.0f} keV, k_max {k_max} 1/A). Do not edit by hand.",
        f"export const ENERGY_EV = {int(ENERGY_EV)};",
        "export const PRESETS: Record<string, string> = {",
    ]
    for name, data in presets.items():
        payload = json.dumps(data, separators=(",", ":"))
        lines.append(f"  {json.dumps(name)}: {json.dumps(payload)},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def parse_ts(text: str) -> dict[str, dict]:
    """Read the payloads back from a presets.ts module."""
    body = text[text.index("{", text.index("PRESETS")) : text.rindex("}") + 1]
    body = re.sub(r",\s*}$", "}", body)
    return {name: json.loads(payload) for name, payload in json.loads(body).items()}


def _decode(field: str, value: str) -> np.ndarray:
    raw = base64.b64decode(value)
    return np.frombuffer(raw, dtype=np.int16 if field == "hkl_i16" else np.float32)


def compare(new: dict[str, dict], old: dict[str, dict]) -> list[str]:
    """List the differences between two preset sets beyond float32 round-off."""
    problems = []
    if list(new) != list(old):
        problems.append(f"structure list differs: {list(new)} vs {list(old)}")
    for name in set(new) & set(old):
        a, b = new[name], old[name]
        if list(a) != list(b):
            problems.append(f"{name}: keys differ: {list(a)} vs {list(b)}")
            continue
        for key in a:
            va, vb = a[key], b[key]
            if va == vb:
                continue
            if key == "hkl_i16":
                if not np.array_equal(_decode(key, va), _decode(key, vb)):
                    problems.append(f"{name}.{key}: reflection indices differ")
            elif key in _FLOAT32_FIELDS:
                xa, xb = _decode(key, va), _decode(key, vb)
                scale = max(float(np.abs(xb).max(initial=0.0)), 1e-30)
                if xa.shape != xb.shape or np.abs(xa - xb).max(initial=0.0) > 1e-5 * scale:
                    problems.append(f"{name}.{key}: values differ beyond float32 round-off")
            elif isinstance(va, float) or (isinstance(va, list) and key in _FLOAT64_FIELDS):
                xa, xb = np.asarray(va, float), np.asarray(vb, float)
                if xa.shape != xb.shape or not np.allclose(xa, xb, rtol=1e-6, atol=1e-12):
                    problems.append(f"{name}.{key}: values differ")
            else:
                problems.append(f"{name}.{key}: {va!r} vs {vb!r}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="compare with the committed file")
    parser.add_argument("--output", type=Path, default=OUTPUT, help="presets.ts path")
    args = parser.parse_args(argv)

    presets = generate()
    if args.check:
        problems = compare(presets, parse_ts(args.output.read_text(encoding="utf-8")))
        for line in problems:
            print(line)
        if not problems:
            print(f"ok: {len(presets)} structures match {args.output}")
        return 1 if problems else 0
    args.output.write_text(render_ts(presets), encoding="utf-8")
    print(f"wrote {args.output} ({len(presets)} structures)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
