#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: scripts/widget_local_signoff.sh [--quick] [--full] [--browser] [--performance] [--skip-docs] [--artifact-dir DIR]

Canonical local automation before saying widget work is ready.

Default gates:
  - repo hygiene and size guards
  - npm run build
  - PYTHONPATH=src:. pytest -q
  - scripts/widget_html_smoke.py
  - jupyter-book build docs --all

Options:
  --quick        Run size guards, frontend build, focused HTML protocol tests,
                 and HTML export smoke. Skip full pytest/docs build.
  --full         Also run npm typecheck/test and widget_release_check.sh --skip-wheel.
  --browser      Drive generated HTML exports in Chromium, verify nonblank
                 canvases, exercise basic controls, and write screenshots.
  --performance  Run real-data Show2D/Show3D export performance smoke.
  --skip-docs    Skip docs build.
  --artifact-dir DIR
                 Write reports and generated HTML under DIR. By default, use
                 /tmp/quantem-widget-local-signoff/<timestamp>.
EOF
}

mode=default
browser=0
performance=0
skip_docs=0
artifact_dir=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help|-h) usage; exit 0 ;;
    --quick) mode=quick ;;
    --full) mode=full ;;
    --browser) browser=1 ;;
    --performance) performance=1 ;;
    --skip-docs) skip_docs=1 ;;
    --artifact-dir)
      if [[ $# -lt 2 ]]; then
        echo "--artifact-dir requires a path" >&2
        exit 2
      fi
      artifact_dir="$2"
      shift
      ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
  shift
done

cd "$(dirname "$0")/.."

if [[ -z "$artifact_dir" ]]; then
  artifact_dir="/tmp/quantem-widget-local-signoff/$(date +%Y%m%d-%H%M%S)"
fi
mkdir -p "$artifact_dir"
artifact_dir="$(cd "$artifact_dir" && pwd)"
start_unix="$(date +%s)"
branch="$(git branch --show-current 2>/dev/null || echo unknown)"
commit="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"

echo "== quantem.widget local signoff =="
echo "repo: $(pwd)"
echo "branch: $branch"
echo "commit: $commit"
echo "artifact dir: $artifact_dir"
git status --short

echo "== size guards =="
python scripts/check_large_files.py
python scripts/check_notebook_sizes.py

echo "== frontend build =="
npm run build

if [[ "$mode" == "quick" ]]; then
  echo "== focused pytest =="
  PYTHONPATH=src:. pytest -q \
    tests/test_html_export_protocol.py \
    tests/test_showfolder.py \
    tests/test_automation_scripts.py
else
  echo "== full pytest =="
  PYTHONPATH=src:. pytest -q
fi

echo "== HTML export smoke matrix =="
PYTHONPATH=src:. python scripts/widget_html_smoke.py --artifact-dir "$artifact_dir/html-smoke"

if [[ "$browser" -eq 1 ]]; then
  echo "== browser-drive HTML smoke =="
  PYTHONPATH=src:. python scripts/widget_browser_smoke.py --artifact-dir "$artifact_dir/html-smoke"
fi

if [[ "$performance" -eq 1 ]]; then
  echo "== real-data performance smoke =="
  PYTHONPATH=src:. python scripts/widget_performance_smoke.py --artifact-dir "$artifact_dir/performance"
fi

if [[ "$skip_docs" -eq 0 && "$mode" != "quick" ]]; then
  echo "== docs build =="
  jupyter-book build docs --all
fi

if [[ "$mode" == "full" ]]; then
  echo "== frontend typecheck/test =="
  npm run typecheck
  npm test

  echo "== release check without wheel =="
  scripts/widget_release_check.sh --skip-wheel
fi

end_unix="$(date +%s)"
duration="$((end_unix - start_unix))"
if [[ "$skip_docs" -eq 0 && "$mode" != "quick" ]]; then
  docs_status="built"
else
  docs_status="skipped"
fi
cat > "$artifact_dir/index.html" <<EOF
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>quantem.widget local signoff</title>
  <style>
    body { font-family: system-ui, sans-serif; margin: 24px; color: #18202a; line-height: 1.45; }
    table { border-collapse: collapse; margin-top: 12px; min-width: 520px; }
    th, td { border: 1px solid #ccd3db; padding: 6px 8px; text-align: left; }
    th { background: #f3f5f7; }
    code { background: #f5f7f9; padding: 2px 4px; border-radius: 4px; }
  </style>
</head>
<body>
  <h1>quantem.widget local signoff</h1>
  <p>This report is generated by <code>scripts/widget_local_signoff.sh</code>.
  Use it as the visual handoff after an agent or human runs the readiness gates.</p>
  <table>
    <tbody>
      <tr><th>Repository</th><td>$(pwd)</td></tr>
      <tr><th>Branch</th><td>$branch</td></tr>
      <tr><th>Commit</th><td>$commit</td></tr>
      <tr><th>Mode</th><td>$mode</td></tr>
      <tr><th>Browser smoke</th><td>$browser</td></tr>
      <tr><th>Performance smoke</th><td>$performance</td></tr>
      <tr><th>Docs build</th><td>$docs_status</td></tr>
      <tr><th>Duration</th><td>${duration}s</td></tr>
    </tbody>
  </table>
  <h2>Visual Reports</h2>
  <ul>
    <li><a href="html-smoke/index.html">HTML export smoke matrix</a></li>
EOF

if [[ "$browser" -eq 1 ]]; then
  cat >> "$artifact_dir/index.html" <<EOF
    <li><a href="html-smoke/browser-smoke.html">Browser-drive HTML smoke</a></li>
EOF
fi

if [[ "$performance" -eq 1 ]]; then
  cat >> "$artifact_dir/index.html" <<EOF
    <li><a href="performance/index.html">Real-data Show2D/Show3D performance smoke</a></li>
EOF
fi

cat >> "$artifact_dir/index.html" <<EOF
  </ul>
  <h2>What Passed</h2>
  <ul>
    <li>Repository size guards</li>
    <li>Frontend build</li>
    <li>Python tests for the selected mode</li>
    <li>Standalone HTML export smoke for every export-capable widget</li>
EOF

if [[ "$browser" -eq 1 ]]; then
  cat >> "$artifact_dir/index.html" <<EOF
    <li>Browser-drive smoke for generated HTML exports</li>
EOF
fi

if [[ "$skip_docs" -eq 0 && "$mode" != "quick" ]]; then
  cat >> "$artifact_dir/index.html" <<EOF
    <li>Documentation build</li>
EOF
fi

if [[ "$mode" == "full" ]]; then
  cat >> "$artifact_dir/index.html" <<EOF
    <li>Frontend typecheck/test</li>
    <li>Release check without wheel</li>
EOF
fi

cat >> "$artifact_dir/index.html" <<EOF
  </ul>
</body>
</html>
EOF

echo "== local signoff passed =="
echo "Signoff report: $artifact_dir/index.html"
